### PR TITLE
Add length of the whole pool

### PR DESCRIPTION
**Pull request by victoriatomzik**
While scraping, I've been missing an indication on where am I during my task, so I wanted to see on which url I am left from the whole pool of urls, example: [12/34].  Let me know, what do you think about it.

Also, now I'm thinking, maybe instead of `len(uri_dic)` it'd be better to use the `count` variable? Let me know what do you think about it.

### CODE REVIEW

**Comment by eggplants** [comment]
Thank you for your PR! (Wait a sec, I'm checking...)

**Comment by eggplants** [comment]
> indication on where am I during my task

LGTM

> maybe instead of len(uri_dic) it'd be better to use the count variable? 

Considering the slight amount of computation, I think it's better to do so.
Yes, please😊

**Comment by eggplants** [comment]
In line 118, Archive.py, please add: `dic_size = len(uri_dic)` and replace line 129 and 138 to this.

**Comment by victoriatomzik** [comment]
Done!

**Comment by eggplants** [comment]
Thank you so much!

**Comment by victoriatomzik** [comment]
My pleasure. I love this project, so if you need any help, let me know! You can write me an e-mail: wiktoria.tomzik@protonmail.com

**Pull request merged**
